"""Initial migration with extensions.py fix

Revision ID: 103dbf4c3e3f
Revises: 
Create Date: 2025-05-05 20:12:05.023749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103dbf4c3e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('job_cluster_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_question', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['job_cluster_id'], ['job_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_selected_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['job_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('first_question', sa.String(length=300), nullable=False),
    sa.Column('second_question', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('user_selected_clusters')
    op.drop_table('subgroups')
    op.drop_table('user_responses')
    op.drop_table('job_clusters')
    # ### end Alembic commands ###
