"""Add attribute scores to JobCluster

Revision ID: 2f93b48efb2c
Revises: 65482e956346
Create Date: 2025-05-12 23:50:20.819927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f93b48efb2c'
down_revision = '65482e956346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('physical', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('leadership', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('creativity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('logic', sa.Integer(), nullable=False))

    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz_sessions', ['session_id'], ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('job_clusters', schema=None) as batch_op:
        batch_op.drop_column('logic')
        batch_op.drop_column('creativity')
        batch_op.drop_column('leadership')
        batch_op.drop_column('physical')
        batch_op.drop_column('social')

    # ### end Alembic commands ###
