"""Add explicit names to FriendRequest foreign keys

Revision ID: 3c82735d92b6
Revises: 5564ae18c6a0
Create Date: 2025-05-14 14:39:20.141132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c82735d92b6'
down_revision = '5564ae18c6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz_sessions', ['session_id'], ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
