"""Next change

Revision ID: 67ea99116582
Revises: 49cbdeaf7595
Create Date: 2025-05-09 09:44:11.014476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ea99116582'
down_revision = '49cbdeaf7595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_clusters', schema=None) as batch_op:
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
