"""Add cluster_question to JobCluster

Revision ID: 8b4852b548e2
Revises: 103dbf4c3e3f
Create Date: 2025-05-06 18:40:59.771451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4852b548e2'
down_revision = '103dbf4c3e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_question', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_clusters', schema=None) as batch_op:
        batch_op.drop_column('cluster_question')

    # ### end Alembic commands ###
