"""Add cluster_question

Revision ID: b94b56cd569b
Revises: 8b4852b548e2
Create Date: 2025-05-06 18:42:39.191172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94b56cd569b'
down_revision = '8b4852b548e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=300), nullable=True))
        batch_op.drop_column('cluster_question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_question', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('question')

    # ### end Alembic commands ###
